version: "3.9"

services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      CLUSTER_ID: 8PSE0GzTRqGdlGcX0TWKJg
      KAFKA_HEAP_OPTS: "-Xmx400m -Xms400m"
    networks:
      - microservices-net

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_READONLY: "false"
      KAFKA_CLUSTERS_0_TOPIC_AUTO_CREATE: "true"
    networks:
      - microservices-net

  payment-service:
    build:
      context: ./Service/payment-service
    container_name: payment-service
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BROKERS=kafka:9092
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - kafka
    restart: unless-stopped
    networks:
      - microservices-net

  email-service:
    build:
      context: ./Service/email-service
    container_name: email-service
    environment:
      - KAFKA_BROKERS=kafka:9092
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_SECURE=false
      - EMAIL_USER=soniwdew@gmail.com
      - EMAIL_PASSWORD=vlwp zcal mrrw bzix
    depends_on:
      - kafka
    restart: unless-stopped
    networks:
      - microservices-net

  order-service:
    build:
      context: ./Service/order-service
    container_name: order-service
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped
    networks:
      - microservices-net

  analytic-service:
    build:
      context: ./Service/analytic-service
    container_name: analytic-service
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped
    networks:
      - microservices-net

  api-gateway:
    build:
      context: ./Service/api-gateway
    container_name: api-gateway
    ports:
      - "7000:7000"
    environment:
      - PAYMENT_SERVICE_BASE=http://payment-service:8000/payment-service
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - payment-service
    restart: unless-stopped
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
